# Geração de instâncias

In [1]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB
from udgp import M1, M2, M4, M5, Instance

In [2]:
# from os import environ
# environ["HTTPS_PROXY"] = "http://pbraun:Br74123698Aun@10.1.60.11:80"
env = gp.Env()

Set parameter Username
Academic license - for non-commercial use only - expires 2024-07-25


In [3]:
# seed: 1234567
instance = Instance.artificial_molecule(6, freq=True, seed=1234567)
instance.view_input()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [4]:
import time
from IPython.display import clear_output

instance.reset()
previous_a = []

i = 1
while not instance.is_solved():
# while instance.fixed_n < instance.n:
    clear_output(wait=True)
    print("=================")
    print(f"TENTATIVA {i}")
    print("=================")

    instance.reset()
    m = M4(instance, nx=4, previous_a=previous_a, env=env)
    m.optimize()
    print(instance.a_indices.T)
    previous_a.append([(i, j, k) for i, j, k in instance.a_indices])

    # instance.reset_with_core("mock")

    print("CORE")

    broken = False
    while instance.fixed_n < instance.n and not broken:
        print(f"  {instance.fixed_n} átomos")

        status = GRB.LOADED
        while status != GRB.OPTIMAL:
            m = M4(instance, nx=1, env=env)
            m.relax()
            m.optimize()
            status = m.Status
    
            if status == GRB.INFEASIBLE:
                broken = True
                break

    time.sleep(1)
    i += 1

instance.view()


TENTATIVA 2
novas distâncias: [1.5  1.5  1.5  1.5  2.45 2.45 2.87 2.87 3.46 3.46]
distâncias disponíveis: [1.5  1.5  1.5  1.5  1.5  2.45 2.45 2.45 2.45 2.45 2.87 2.87 2.87 2.87
 3.46]
distância 3.4609375 não está na lista: [1.5  2.45 2.87 3.46]
frequências: [1 3 2 0]
erro mínimo: 3.4609375 -> 0.0
coordenadas:
[[ 2.59062023  1.83071398 -1.38368758]
 [ 1.05427059 -0.46222232 -2.16192724]
 [ 0.08932665  0.43132202 -1.43352154]
 [-0.05961127  1.45765715 -0.34965398]]
não puderam ser adicionadas.
[[0 0 0 2 0 0 1 1 0]
 [3 3 4 3 2 2 3 2 1]
 [0 0 0 0 1 1 2 2 3]]
CORE
  1 átomos
novas distâncias: [1.5]
distâncias disponíveis: [1.5  1.5  1.5  1.5  1.5  2.45 2.45 2.45 2.45 2.45 2.87 2.87 2.87 2.87
 3.46]
  2 átomos
novas distâncias: [1.5 1.5]
distâncias disponíveis: [1.5  1.5  1.5  1.5  1.5  2.45 2.45 2.45 2.45 2.45 2.87 2.87 2.87 2.87
 3.46]
  3 átomos
novas distâncias: [1.5  2.87 2.87]
distâncias disponíveis: [1.5  1.5  1.5  1.5  1.5  2.45 2.45 2.45 2.45 2.45 2.87 2.87 2.87 2.87
 3.46]
  4 átom

KeyboardInterrupt: 

In [13]:
from udgp.utils import *

from scipy.spatial.distance import pdist

coords = np.array([
    [0, 0, 0],
    [ 2.59062023,  1.83071398, -1.38368758],
    [ 1.05427059, -0.46222232, -2.16192724],
    [ 0.08932665,  0.43132202, -1.43352154],
    [-0.05961127,  1.45765715, -0.34965398],
])

y = np.array([
    [0, 0, 0],
])

x = np.array([
    [ 2.59062023,  1.83071398, -1.38368758],
    [ 1.05427059, -0.46222232, -2.16192724],
    [ 0.08932665,  0.43132202, -1.43352154],
    [-0.05961127,  1.45765715, -0.34965398],
])

print(np.sort(pdist(coords)).round(2))

print(coords_new_dists(y, x))


[1.5  1.5  1.5  1.5  2.45 2.87 2.87 2.87 2.87 3.46]
[1.5  1.5  1.5  1.5  2.45 2.45 2.87 2.87 3.46 3.46]
