# Geração de instâncias

In [1]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB
from udgp import M1, M2, M4, M5, Instance

In [2]:
# from os import environ
# environ["HTTPS_PROXY"] = "http://pbraun:Br74123698Aun@10.1.60.11:80"
env = gp.Env()

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2372514
Academic license - for non-commercial use only - registered to braun@cos.ufrj.br


In [3]:
# seed: 1234567
# instance = Instance.artificial_molecule(10, freq=True, seed=1234567)
instance = Instance.lj_cluster(7, freq=True)
instance.view_input()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [4]:
print(instance.dists)
print(instance.freqs)

[1.12 1.15 1.82]
[15  1  5]


In [42]:
instance.reset()
m = M4(
    instance, 
    nx=4, 
    env=env,
)
m.optimize()
instance.view()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [43]:
print(instance.dists)
print(instance.freqs)

[1.12 1.15 1.82]
[7 0 4]


In [46]:
m = M4(instance, nx=1, ny=4, env=env)
solved = m.optimize()
instance.view()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [49]:
m = M4(instance, nx=1, ny=5, env=env)
solved = m.optimize()
instance.view()

GurobiError: Recv failure: Connection was reset (code 35, command POST https://token.gurobi.com/api/v1/tokens)

# Heurística

In [8]:
from IPython.display import clear_output

instance.reset()

previous_a = []

i = 1
while not instance.is_solved():
# while instance.fixed_n < instance.n:
    clear_output(wait=True)
    print("=================")
    print(f"TENTATIVA {i}")
    print("=================")
    i += 1

    instance.reset()
    m_core = M4(instance, nx=4, env=env)
    for a_indices in previous_a:
        m_core.addConstr(
            gp.quicksum(m_core.a[i, j, k] for i, j, k in a_indices) 
            <= len(a_indices) - 1
        )
    m_core.optimize()

    previous_a.append(instance.a_indices.tolist())
    
    # instance.reset_with_core("mock")
    
    print("CORE")

    broken = False
    while instance.fixed_n < instance.n and not broken:
        repr(instance.view())
        print(f"  {instance.fixed_n} átomos")

        solved = False
        while not solved:
            m = M2(instance, nx=1, env=env)
            # m.relax()
            solved = m.optimize()
    
            if m.Status == GRB.INFEASIBLE:
                broken = True
                # previous_a.append([(i, j, k) for i, j, k in instance.a_indices])
                break

instance.view()


TENTATIVA 1
CORE
  5 átomos
  6 átomos
  7 átomos
  8 átomos


: 

: 